### ISSUE TITLE
DCOI schema, historical  data

### ISSUE THREAD

**Issue by hakan-lidstrom** [WhiteHouse/CIOmanagement#11]
The description of the DCOI schema lists element 5. Historical costs, cost savings, and cost avoidances due to data center consolidation and optimization through fiscal year 2015;
I don't see any fields for historical values in the table below, or in the actual schema. Is it missing, or is it just me missing it?

**Comment by malissal** [comment]
Thanks for the question @hakan-lidstrom. The field name is historicalCostSavings - let me know if you need any further clarification!

**Comment by hakan-lidstrom** [comment]
Malissa,

Are you implying that there was a very recent change to the schema? This field was not in the schema when USAID poste its plan a few days ago.

Thanks,

[Octo Icon]

Håkan Lidström
Contractor supporting the USAID Office of the CIO
Octo Consulting | Business Enterprise Architect

tel +1 571 297-8920 | mobile +1 301 266 0608
hakan.lidstrom@octoconsulting.commailto:hakan.lidstrom@octoconsulting.com

[CMMI Dev 4]  [Scaled Agile Certification]
[GSA Contract Vehicle] http://www.octoconsulting.com/contract-vehicles/gsa-alliant-small-business Alliant Small Business  [CI0-SP3 Small Business]  http://www.octoconsulting.com/contract-vehicles/cio-sp3-gwac CIO-SP3 Small Business  [Eagle II]  http://www.octoconsulting.com/contract-vehicles/dhs-eagle-ii Eagle II

**Comment by malissal** [comment]
@hakan-lidstrom There was a lot of confusion about the previous name ‘lifecycleCostSavingsEstimated’ so we clarified that we’re asking for historical cost and cost savings information for the FDCCI years (2010-2015) and changed it a week ago - sorry for the communication issue. All you need to do is change the name of that field to historicalCostSavings and we will accept it.
