### ISSUE TITLE
Inter-agency - How do you apply?

### ISSUE THREAD

**Issue by kklinner** [WhiteHouse/CIOmanagement#12]
The new DCOI memo dated August 1, 2016 says (page 4) "Data centers that OGP (GSA) determines satisfactory in all of their operating standards will be designated as inter-agency shared services providers."  What is the process of applying for a OGP review?

**Comment by dpomeroy** [comment]
Thanks for the inquiry! Currently OGP is working with OMB to solidify the review process. To stay up to date on Data Center issues, please join our listserv by emailing listserv@listserv.gsa.gov with no subject and "subscribe datacenters" in the body.
