### ISSUE TITLE
Where are the Document Files for DCOI Strategic Plan 

### ISSUE THREAD

**Issue by djharrity** [WhiteHouse/CIOmanagement#16]
Per the management.cio.gov page for DCOI, it mentions using "one of the two templates given in the document file provided on this page".  What document files, I don't see a document file to use?

Part 6 of agencies’ DCOI Strategic Plans may be fulfilled using one of the two templates given in the document file provided on this page. These must be filled out, signed by agencies’ CIOs, and submitted via email to the OFCIO@omb.eop.gov inbox, CC’ing the agency’s OMB Desk Officer, no later than September 30, 2016.

**Comment by malissal** [comment]
@djharrity the template file is provided above the schema table under the heading **[CIO DCOI Certification Statement Templates](https://management.cio.gov/assets/docs/DCOI_StrategicPlans_part6_cioStatement.docx)** (also linked directly here as well). I hope that helps!
