### ISSUE TITLE
Why are all the implementation plans in .json files?

### ISSUE THREAD

**Issue by eberlyn** [WhiteHouse/CIOmanagement#17]
Why are all of the "Public FITARA Implementation Plans" in .json files? I can no longer read them. When they were in plan text my computer could read them. They are helpful for seeing what other Agencies are doing.

**Comment by gbinal** [comment]
Hi @eberlyn.  There are a few benefits to JSON, but they revolve most of all around making the information in the data machine-friendly.  Having data fields and standardized structures for them let us do a lot that we couldn't do if it was free form.  In the end, it allows a ton of re-use of the data in useful ways, including making presentation layers for humans to read but also allow machine-processing.  

One big help I found was using a browser extension to 'beautify' the JSON.  At that point, it's human readable to me.  Here are examples for [Chrome](https://chrome.google.com/webstore/search/json%20formatter) and [Firefox](https://addons.mozilla.org/en-US/firefox/search/?q=json+formatter&appver=&platform=).  Those are nice b/c they can run automatically whenever you load a JSON file.  

If you have trouble using the extensions, there are also [a bunch of websites](https://www.google.com/search?q=json+formatter&oq=json+formatter&aqs=chrome.0.0l6.2063j0j7&sourceid=chrome&ie=UTF-8) that let you do it quickly and easily as well.
