### ISSUE TITLE
Dead link on homepage of https://github.com/WhiteHouse

### ISSUE THREAD

**Issue by iguanaus** [WhiteHouse/CIOmanagement#35]
<img width="1268" alt="Screen Shot 2020-04-18 at 1 54 39 AM" src="https://user-images.githubusercontent.com/5752769/79629422-ade63e80-8117-11ea-800e-f15502694273.png">
<img width="630" alt="Screen Shot 2020-04-18 at 1 54 31 AM" src="https://user-images.githubusercontent.com/5752769/79629423-ae7ed500-8117-11ea-9bc9-37e45b9b5610.png">

I don't know if this repo is still maintained, but the above link is a deadlink.

Thank you for your hard work and service.

**Comment by Nintendofan885** [comment]
Looks like it's been changed to 'https://www.whitehouse.gov/'

**Comment by Nintendofan885** [comment]
Looks like it's been changed to https://www.whitehouse.gov/
