### ISSUE TITLE
Footnote links not rendering correctly

### ISSUE THREAD

**Issue by vdavez** [WhiteHouse/CIOmanagement#6]
The footnotes are written in markdown but are wrapped in html blocks. Accordingly, when rendering, the links in the footnotes don't show up as links and instead look like the following:

<img width="1121" alt="screen shot 2016-07-10 at 5 26 39 am" src="https://cloud.githubusercontent.com/assets/4153048/16712768/26d175aa-465f-11e6-8994-0267731f02c7.png">

Given that the footnotes are written in html to ease the anchoring between text and the footnotes, to fix this, I propose just converting the markdown in the footnotes into html.

**Comment by malissal** [comment]
Thanks for the catch @vzvenyach! Fixed the formatting so the links now render correctly.
